### ISSUE TITLE
call route with pagination params returns 'bad request'

### ISSUE THREAD

**Issue by T1m1** [locator-kn/ark-chat#4]
I tryed to implement pagination for messages. 

http://locator-app.com/api/v1/r/messages/05888095f626a4afb3b11568acfb63ee?page=1&elements=2

returns 

{
"statusCode": 400,
"error": "Bad Request",
"message": "CouchError: not_found: missing_named_view"
}

**Comment by SteffenGorenflo** [comment]
fixed
